// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzz3wNL4rnI8wD5y02EFkzGnQULIiqtgU',
    appId: '1:906082614973:web:bdd5a904ae5f5ab18301d4',
    messagingSenderId: '906082614973',
    projectId: 'expense-tracker-dc6f2',
    authDomain: 'expense-tracker-dc6f2.firebaseapp.com',
    storageBucket: 'expense-tracker-dc6f2.firebasestorage.app',
    measurementId: 'G-XT1MJ1DFCT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKs0cHwBMp6F5RkDc4qfmYvfS8ah0ogOo',
    appId: '1:906082614973:android:3867b3747f9a95668301d4',
    messagingSenderId: '906082614973',
    projectId: 'expense-tracker-dc6f2',
    storageBucket: 'expense-tracker-dc6f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgKmltw8PFdm1pFuHhe7PFq3A6pb1-TUU',
    appId: '1:906082614973:ios:deefd065ced87ac68301d4',
    messagingSenderId: '906082614973',
    projectId: 'expense-tracker-dc6f2',
    storageBucket: 'expense-tracker-dc6f2.firebasestorage.app',
    iosBundleId: 'com.example.exer8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgKmltw8PFdm1pFuHhe7PFq3A6pb1-TUU',
    appId: '1:906082614973:ios:deefd065ced87ac68301d4',
    messagingSenderId: '906082614973',
    projectId: 'expense-tracker-dc6f2',
    storageBucket: 'expense-tracker-dc6f2.firebasestorage.app',
    iosBundleId: 'com.example.exer8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzz3wNL4rnI8wD5y02EFkzGnQULIiqtgU',
    appId: '1:906082614973:web:2c671516574cdcb48301d4',
    messagingSenderId: '906082614973',
    projectId: 'expense-tracker-dc6f2',
    authDomain: 'expense-tracker-dc6f2.firebaseapp.com',
    storageBucket: 'expense-tracker-dc6f2.firebasestorage.app',
    measurementId: 'G-6PMDEKEY1J',
  );
}
